server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # SPA: любой неизвестный путь отдаём как index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    location /healthz {
        access_log off;
        add_header Content-Type text/plain;
        return 200 'ok';
    }

    gzip on;
    gzip_types text/css application/javascript application/json image/svg+xml;
    gzip_min_length 1024;
}
